export const ReferenceExecuteFileReferenceProvider = 'ExtensionHostReference.executeFileReferenceProvider'
export const ReferenceExecuteReferenceProvider = 'ExtensionHostReference.executeReferenceProvider'
export const ReferenceExecuteReferenceProvider2 = 'ExtensionHostReference.executeReferenceProvider2'
