export const ReferenceExecuteFileReferenceProvider = 'ExtensionHostReference.executeFileReferenceProvider'
export const ReferenceExecuteReferenceProvider = 'ExtensionHostReference.executeReferenceProvider'
