export const FileIcon = 'FileIcon'
export const Highlight = 'Highlight'
export const Label = 'Label'
export const LocationList = 'LocationList'
export const LocationsMessage = 'LocationsMessage'
export const TreeItem = 'TreeItem'
