export const NoResults = 'No Results'
export const OneResultInOneFile = '1 result in 1 file'
export const ManyResultsInOneFile = '{PH1} results in 1 file'
export const ManyResultsInManyFiles = '{PH1} results in {PH2} files'
export const Locations = 'Locations'
export const Refresh = 'Refresh'
export const Clear = 'Clear'
export const CollapseAll = 'Collapse All'
