export const commandIds: readonly string[] = [
  'create',
  'dispose',
  'focusFirst',
  'focusIndex',
  'focusLast',
  'focusNext',
  'focusPrevious',
  'getKeyBindings',
  'handleClickReference',
  'restoreState',
  'saveState',
  'selectIndex',
  'terminate',
]
